spring.datasource.url=jdbc:postgresql://localhost:5433/pocdb
spring.datasource.username=poc
spring.datasource.password=poc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect